# Generated by Django 5.2.7 on 2025-10-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_comment_share_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL unique du profil (ex: hiba-louhibi)', max_length=100, null=True, unique=True),
        ),
    ]
