# Generated by Django 5.2.7 on 2025-10-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_avis'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='detected_language',
            field=models.CharField(blank=True, help_text='Langue détectée (ex: fr, ar, en)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='voice_transcription',
            field=models.TextField(blank=True, help_text='Transcription automatique de la note vocale', null=True),
        ),
    ]
