# Generated by Django 5.2.7 on 2025-10-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_detected_language_post_voice_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_category',
            field=models.CharField(blank=True, help_text='Catégorie détectée (beach, mountain, city, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image_category_fr',
            field=models.CharField(blank=True, help_text='Catégorie en français', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image_confidence',
            field=models.FloatField(blank=True, help_text='Confiance de la prédiction (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image_tags',
            field=models.JSONField(blank=True, help_text='Tags automatiques générés', null=True),
        ),
    ]
