# Generated by Django 5.2.7 on 2025-10-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_detected_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='detected_country',
            field=models.CharField(blank=True, help_text='Pays détecté', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='detected_landmark',
            field=models.CharField(blank=True, help_text="Point d'intérêt détecté", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='detection_confidence',
            field=models.FloatField(blank=True, help_text='Niveau de confiance de la détection', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='detection_method',
            field=models.CharField(blank=True, help_text='Méthode de détection du pays', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude du post', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude du post', null=True),
        ),
    ]
