# Generated by Django 4.2.25 on 2025-10-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_detected_country_post_detected_landmark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='detected_country',
            field=models.CharField(blank=True, help_text='Pays détecté automatiquement', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='detected_landmark',
            field=models.CharField(blank=True, help_text="Monument ou lieu célèbre détecté dans l'image", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='detection_confidence',
            field=models.FloatField(blank=True, help_text='Niveau de confiance de la détection (0-1)', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='detection_method',
            field=models.CharField(blank=True, help_text="Méthode utilisée pour la détection (ex: 'exif', 'landmark', 'ocr')", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude GPS du lieu de la publication', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude GPS du lieu de la publication', null=True),
        ),
    ]
