# Generated by Django 5.2.7 on 2025-10-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20251030_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='flouci_payment_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='flouci_transaction_id',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(choices=[('STRIPE', 'Stripe (International)'), ('MANUAL', 'Manuel (Admin)')], default='STRIPE', max_length=20),
        ),
    ]
