# Generated by Django 5.2.7 on 2025-10-30 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_paymenthistory_flouci_payment_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(help_text='Nom de la destination', max_length=200)),
                ('country', models.CharField(help_text='Pays', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bucket_list/')),
                ('description', models.TextField(blank=True, help_text='Pourquoi cette destination ?', null=True)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('target_date', models.DateField(blank=True, help_text='Date souhaitée de visite', null=True)),
                ('visited_date', models.DateField(blank=True, help_text='Date de visite réelle', null=True)),
                ('status', models.CharField(choices=[('PLANNED', '📅 Planifié'), ('IN_PROGRESS', '✈️ En cours'), ('COMPLETED', '✅ Visité'), ('CANCELLED', '❌ Annulé')], default='PLANNED', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, '🔥 Très haute'), (2, '⭐ Haute'), (3, '📌 Moyenne'), (4, '💭 Basse')], default=3)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ai_tags', models.JSONField(blank=True, help_text='Tags générés par IA', null=True)),
                ('ai_recommendations', models.TextField(blank=True, help_text='Recommandations IA', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Destination de rêve',
                'verbose_name_plural': 'Bucket List',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('estimated_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('PLANNING', 'En planification'), ('CONFIRMED', 'Confirmé'), ('ONGOING', 'En cours'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='PLANNING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket_list_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='core.bucketlist')),
                ('participants', models.ManyToManyField(blank=True, related_name='joined_trips', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voyage',
                'verbose_name_plural': 'Voyages',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Solde disponible', max_digits=10)),
                ('currency', models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dollar ($)'), ('GBP', 'Livre Sterling (£)'), ('TND', 'Dinar Tunisien (TND)'), ('MAD', 'Dirham Marocain (MAD)')], default='EUR', max_length=3)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_saved', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portefeuille',
                'verbose_name_plural': 'Portefeuilles',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', '💰 Dépôt'), ('WITHDRAWAL', '💸 Retrait'), ('TRANSFER', '🔄 Transfert'), ('EXPENSE', '🛒 Dépense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trip')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
