# Generated by Django 4.2.25 on 2025-10-30 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_userprofile_password_reset_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password_reset_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password_reset_expires_at',
        ),
        migrations.CreateModel(
            name='TwoFactorCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('login', 'Login')], default='login', max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'purpose', 'expires_at'], name='core_twofac_user_id_50d710_idx')],
            },
        ),
    ]
