# Generated by Django 4.2.25 on 2025-10-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_chatroom_message_chatroommembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Utilisateur actuellement en ligne'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, help_text="Dernière activité de l'utilisateur"),
        ),
    ]
