# Generated by Django 4.2.25 on 2025-10-30 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile_is_online_userprofile_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_seen',
        ),
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat/attachments/')),
                ('original_name', models.CharField(help_text='Nom original du fichier', max_length=255)),
                ('file_type', models.CharField(help_text='Type MIME du fichier', max_length=100)),
                ('file_size', models.PositiveIntegerField(help_text='Taille du fichier en bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.message')),
            ],
            options={
                'verbose_name': 'Fichier de message',
                'verbose_name_plural': 'Fichiers de messages',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
