# Generated by Django 4.2.25 on 2025-10-30 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_remove_userprofile_is_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sentiment_emoji',
            field=models.CharField(default='😐', help_text='Emoji représentant le sentiment', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='sentiment_label',
            field=models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', help_text='Sentiment détecté du message', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='sentiment_score',
            field=models.FloatField(default=0.0, help_text='Score de confiance du sentiment'),
        ),
        migrations.AlterField(
            model_name='message',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
