# Generated by Django 4.2.25 on 2025-10-30 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_message_sentiment_emoji_message_sentiment_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read_by',
            field=models.ManyToManyField(blank=True, help_text='Utilisateurs qui ont lu ce message', related_name='read_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
