# Generated by Django 4.2.25 on 2025-10-29 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('report_type', models.CharField(choices=[('inappropriate', '🔞 Inapproprié'), ('spam', '💬 Spam ou publicité'), ('harassment', '😡 Harcèlement'), ('fake', '⚠️ Fausse information'), ('other', '🚫 Autre')], max_length=20, verbose_name='Type de signalement')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message supplémentaire')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('resolved', 'Résolu'), ('ignored', 'Ignoré')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-created_at'],
            },
        ),
    ]
